application: javascriptbeats
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /lib
  static_dir: lib

- url: /src
  static_dir: src

- url: /test\.html
  static_files: edit2.html
  upload: edit2\.html

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.1"

